// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY ?? import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    "Supabase environment variables are required: VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY or VITE_SUPABASE_PUBLISHABLE_KEY"
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/supabase";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Listen for token refresh failures and sign out to avoid repeated invalid-refresh loops.
// This helps when the stored refresh token was revoked or rotated server-side.
try {
  supabase.auth.onAuthStateChange((event) => {
    if (event === 'TOKEN_REFRESH_FAILED') {
      console.warn('Supabase token refresh failed — clearing local session');
      // best-effort sign out and remove stored token to stop refresh retries
      supabase.auth.signOut().catch(() => {});
      try {
        localStorage.removeItem('supabase.auth.token');
      } catch (e) {}
      // don't force a reload here; let the app react to the signed-out state
    }
  });
} catch (e) {
  // ignore if environment doesn't support window/localStorage at import time
}